#!/bin/sh
pkgname=neofetch
version=7.1.0
revision=4
short_desc="Simple system information script (not my software)"
maintainer="Tracker-Friendly <jliwin98@danwin1210.de>"
homepage="https://gitlab.com/evolutionos/neofetch"
license="MIT"
makedepends="make git"
depends="bash"

do_build() {
    echo "Building..."
    # Not needed
}

do_install() {
    echo "Installing..."
    git clone --depth=1 https://gitlab.com/evolutionos/neofetch
    cd neofetch
    mkdir -p ${DESTDIR}/usr/
    make PREFIX=${DESTDIR}/usr/ install
}
