#!/bin/sh
pkgname=neofetch
version=7.1.0
revision=3
short_desc="Simple system information script (not my software)"
maintainer="Tracker-Friendly <jliwin98@pm.me>"
homepage="https://github.com/evolution-linux/neofetch"
license="MIT"
makedepends="make git"
depends="bash"

do_build() {
    echo "Building..."
    # Not needed
}

do_install() {
    echo "Installing..."
    git clone --depth=1 https://github.com/evolution-linux/neofetch
    cd neofetch
    mkdir -p ${DESTDIR}/usr/
    make PREFIX=${DESTDIR}/usr/ install
}
