#!/bin/bash

CONFIG_DIR="/etc/runitctl/"

if [[ -d $CONFIG_DIR ]]; then
  :
else
  mkdir -p $CONFIG_DIR
fi

list_installed_services() {
  ls -1 /etc/sv
}

list_enabled_services() {
  for i in $(ls -1 /etc/sv);
  do
    pushd /etc/sv/$i &>/dev/null
    if [[ $(ls | grep down) = "" ]]; then
      echo "$i"
    else
      :
    fi
    popd &>/dev/null
  done
}

list_disabled_services() {
  comm -23 <(list_installed_services) <(list_enabled_services)
}

enable_service() {
  service="$1"
  if [ -d "/etc/sv/$service" ]; then
    if [ -e "/etc/runit/runsvdir/default/$service/down" ]; then
      echo "Enabling service: $service"
      rm -rf /etc/runit/runsvdir/default/$service/down
      echo "Enabled service: $service"
    else
      echo "Service $service already enabled"
    fi
  else
    echo "Service '$service' not found."
  fi
}

disable_service() {
  service="$1"
  if [ -f "/etc/runit/runsvdir/default/$service/down" ]; then
    echo "Service '$service' is not enabled."
  else
    echo "Disabling service: $service"
    touch /etc/runit/runsvdir/default/$service/down
    echo "Disabled service: $service"
  fi
}

start_service() {
  service="$1"
  if [ -d "/etc/sv/$service" ]; then
    if [ -f "$CONFIG_DIR/$service.conf" ]; then
      echo "Service '$service' is already running."
    else
      echo "Starting service: $service"
      if [ -d "/etc/runit/runsvdir/default/$service" ]; then
        :
      else
        ln -s /etc/sv/$service /etc/runit/runsvdir/default/$service
      fi
      if [ -d "/run/runit/supervise.$service" ]; then
        :
      else
        cp -r /run/runit/supervise.agetty-tty1 /run/runit/supervise.$service
      fi
      touch $CONFIG_DIR/$service.conf
      sv start $service
      echo "Started service: $service"
    fi
  else
    echo "Service '$service' not found."
  fi
}

stop_service() {
  service="$1"
  if [ -f "$CONFIG_DIR/$service.conf" ]; then
    echo "Stopping service: $service"
    sv stop $service &>/dev/null
    rm $CONFIG_DIR/$service.conf
    echo "Stopped service: $service"
  else
    echo "Service '$service' not started or nonexistent."
  fi
}

case "$1" in
  list)
    case "$2" in
      enabled)
        list_enabled_services
        ;;
      disabled)
        list_disabled_services
        ;;
      *)
        list_installed_services
        ;;
    esac
    ;;
  enable)
    if [ -n "$2" ]; then
      enable_service "$2"
    else
      echo "Usage: $0 enable <service>"
      exit 1
    fi
    ;;
  disable)
    if [ -n "$2" ]; then
      disable_service "$2"
    else
      echo "Usage: $0 disable <service>"
      exit 1
    fi
    ;;
  start)
    if [ -n "$2" ]; then
      start_service "$2"
    else
      echo "Usage: $0 start <service>"
      exit 1
    fi
    ;;
  stop)
    if [ -n "$2" ]; then
      stop_service "$2"
    else
      echo "Usage: $0 stop <service>"
      exit 1
    fi
    ;;
  *)
    echo "Usage: $0 <command> [arguments]"
    echo "Commands:"
    echo "  list [enabled|disabled]  List installed, enabled, or disabled services"
    echo "  enable <service>         Enable a service (start at boot)"
    echo "  disable <service>        Disable a service (start at request)"
    echo "  start <service>          Start a service"
    echo "  stop <service>           Stop a service"
    exit 1
    ;;
esac

